#!/bin/bash

# we search for multimedia using present tools...
ls /sys/class/net > PLAYLIST

#killall mplayer

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

# gtkdialog header
echo '<window title="16ton Network app" width-request="329" height-request="245"> <vbox>
<hbox height-request="65">		
		<button>
			<label>wifi link info (highlight desired card)</label>
			<action>xterm -hold -e /opt/hardware-apps/bin/wifi-link-stats.sh &xterm -hold -e /opt/hardware-apps/bin/wifi-link-stats2.sh</action>
		</button>
	<list> <variable>LIST</variable>' > DIALOG

#feed the list
while read theline; do
	#ls "$theline";
	echo "<item>$theline</item>" >> DIALOG;
done < PLAYLIST

# gtkdialog footer

#<action signal="selection-changed">	echo "LIST=\"$LIST\" - selection-changed"</action>
#<action signal="button-press-event">	echo "$(killall mplayer) - button-press-event"	</action>
#<action signal="key-press-event">	echo $(mplayer -quiet "$LIST")" - key-press-event"</action>
echo '
</list>
</hbox>
	<vbox>
	<hbox>
		<button>
			<label>Show info for wifi device PHY</label>
			<action>xterm -hold -e iw phy$ENTRY info</action>
		</button>
		<entry>
			<default>0</default>
			<variable>ENTRY</variable>
		</entry>		
	</hbox>
		<button>
			<label>Show wifi signal strength (uses wavemon)</label>
			<action>xterm -hold -e wavemon</action>
		</button>
		<button>
			<label>arp list without search (no root)</label>
			<action>xterm -hold -e arp -a</action>
		</button>
		<button>
			<label>arp search (requires root)</label>
			<action>pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY xterm -hold -e arp-scan --localnet</action>
		</button>
		<button>
			<label>Exit</label>
		</button>
	</vbox>
</vbox> </window>' >> DIALOG

case $2 in
	-d | --dump) echo "$DIALOG" ;;
	*) $GTKDIALOG -c -f DIALOG ;;
esac
